### ISSUE TITLE
Cannot import s3tk

### ISSUE THREAD

**Issue by kwent** [ankane/s3tk#12]
Hi,

We should be able to directly `import s3tk` and skip cli interaction like:

```python
>> from s3tk import scan
>> scan('my_bucket')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/s3tk/__init__.py", line 389, in scan
    for bucket in fetch_buckets(buckets):
  File "/usr/local/lib/python2.7/site-packages/s3tk/__init__.py", line 82, in fetch_buckets
    return [s3.Bucket(bn) for bn in buckets]
NameError: global name 's3' is not defined
```

Regards

**Comment by ankane** [comment]
Hey @kwent, it's designed to be used as a CLI rather than imported (just happens to be written in Python). Trying to keep the internal API backwards compatible is more than I want to take on. What are you trying to import it for?

**Comment by muffy** [comment]
Running it as a cron job - I spoke to you about this a while ago, there are some buckets we want(?) to have open to the public, but we'd like to run it nightly and have it send a message when it finds a problem. Since these buckets are always flagged, they cause a lot of noise. I found a workaround, but an intentionally-exposed public api to the checks would be nice.
