### ISSUE TITLE
s3tk scan --object-level-logging error

### ISSUE THREAD

**Issue by JRodriguez556** [ankane/s3tk#17]
Ran the s3tk scan with the --object-level-logging flag and received the following error:

```
Traceback (most recent call last):
  File "/usr/local/bin/s3tk", line 7, in <module>
    s3tk.cli()
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/s3tk/__init__.py", line 440, in scan
    event_selectors = fetch_event_selectors() if object_level_logging else {}
  File "/usr/local/lib/python2.7/dist-packages/s3tk/__init__.py", line 408, in fetch_event_selectors
    if trail['IsMultiRegionTrail']:
KeyError: 'IsMultiRegionTrail'
```

**Comment by ankane** [comment]
Thanks @JRodriguez556, should be good now.
